### ISSUE TITLE
Support Prettier v3

### ISSUE THREAD

**Issue by szape89** [bgotink/prettier-plugin-json-formats#14]
Using this plugin together with other plugins already supporting it can lead to conflicting peer dependency. This can be overridden, but it would be still better to properly support the new major version.
Migration guide here: https://github.com/prettier/prettier/wiki/How-to-migrate-my-plugin-to-support-Prettier-v3%3F

**Comment by bgotink** [comment]
Version 0.5.0 now supports prettier v3 (and drops support of v1/v2).
